<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

	public function listAdverts($page, $nbPerPage)
	{
		$qb = $this->createQueryBuilder('a');

  		$qb
     	->orderBy('a.date', 'DESC')
  	;

	$qb
			//On définit l'annonce à partir de laquelle commencer la liste
	  	  ->setFirstResult(($page-1)* $nbPerPage)
	  	  //Définit le nombre d'annonces à afficher par page
	  	  ->setMaxResults($nbPerPage)
  	;

  	return new Paginator($qb, true);
	}

}
